image: node:11.3.0
before_script:
  - mkdir -p ~/.ssh
  - echo $SSH_PRIVATE_KEY
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
create_static:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm run build
  - cd build
  - ls -la
  - git config --global user.email "213991+leeppolis@users.noreply.github.com"
  - git config --global user.name "Gitlab auto-deploy"
  - git init
  - git remote add origin git@github.com:visualizenews/dovematteo.git
  - git add .
  - git commit -m "Ready to deploy"
  # - git push --force origin HEAD:gh-pages
  - git push --force origin master
  artifacts:
    paths:
    - build
  only:
  - master
